# Generated by Django 3.2 on 2021-04-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('genislik', models.DecimalField(decimal_places=5, max_digits=5, max_length=5)),
                ('yukseklik', models.DecimalField(decimal_places=5, max_digits=5, max_length=5)),
                ('agirlik', models.DecimalField(decimal_places=5, max_digits=5, max_length=5)),
                ('uzunluk', models.DecimalField(decimal_places=5, max_digits=5, max_length=5)),
            ],
        ),
    ]
