# Generated by Django 3.2 on 2021-04-13 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20210413_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(max_length=60)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.product')),
            ],
        ),
    ]
